### ISSUE TITLE
Mac Os X release 0.0.8 is not working (and the version number is incorrect)

### ISSUE THREAD

**Issue by facconi** [phonegap/phonegap-app-desktop#196]
When the app starts, the following error is reported:

Uncaught node.js Error

<pre>
ReferenceError: getProjects is not defined
    at HTMLDocument.eval (file:///Applications/PhoneGap.app/Contents/Resources/app.nw/mockup.html:207:9)
    at l (file:///Applications/PhoneGap.app/Contents/Resources/app.nw/js/jquery-2.0.3.min.js:4:24882)
    at Object.c.fireWith [as resolveWith] (file:///Applications/PhoneGap.app/Contents/Resources/app.nw/js/jquery-2.0.3.min.js:4:25702)
    at Function.x.extend.ready (file:///Applications/PhoneGap.app/Contents/Resources/app.nw/js/jquery-2.0.3.min.js:4:2900)
    at HTMLDocument.S (file:///Applications/PhoneGap.app/Contents/Resources/app.nw/js/jquery-2.0.3.min.js:4:553)
</pre>

In the About dialog, the version number is 0.0.7. I have just re-downloaded from GitHub (the file name is PhoneGap-GUI-0.0.8-mac.zip) and it is replicable.

**Comment by camaleo** [comment]
@CodyCodeman: tried your solution and the issue was still there
Unfortunately there is no way to copy the error and I am not sure what error log to open.

However there must be something to prevent the app to work if its installed in a path including spaces, in my case:
/Volumes/Mac\ Mini\ HD/BTSync/shared\ APPs/PhoneGap.app

When I moved the app to:
/Applications/PhoneGap.app

solved my problem.

So I hope for other users that you can fix the handling of spaces in paths in 0.1.2

Thanks!
