### ISSUE TITLE
Mac auto-updater crashing

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-app-desktop#290]
When the `node-webkit-updater` is throwing the following error when it detects that a new version of the PhoneGap Desktop is available.

```
TypeError: Cannot read property 'mac' of undefined
    at updater.download (/Users/hermanw/Documents/HermWong/phonegap-gui/build/PhoneGap/osx/PhoneGap.app/Contents/Resources/app.nw/node_modules/node-webkit-updater/app/updater.js:70:32)
    at file:///Users/hermanw/Documents/HermWong/phonegap-gui/build/PhoneGap/osx/PhoneGap.app/Contents/Resources/app.nw/js/index.js:50:17
    at updater.gotManifest (/Users/hermanw/Documents/HermWong/phonegap-gui/build/PhoneGap/osx/PhoneGap.app/Contents/Resources/app.nw/node_modules/node-webkit-updater/app/updater.js:58:7)
    at Request.self.callback (/Users/hermanw/Documents/HermWong/phonegap-gui/build/PhoneGap/osx/PhoneGap.app/Contents/Resources/app.nw/node_modules/node-webkit-updater/node_modules/request/request.js:121:22)
    at Request.EventEmitter.emit (events.js:107:17)
    at Request.<anonymous> (/Users/hermanw/Documents/HermWong/phonegap-gui/build/PhoneGap/osx/PhoneGap.app/Contents/Resources/app.nw/node_modules/node-webkit-updater/node_modules/request/request.js:985:14)
    at Request.EventEmitter.emit (events.js:126:20)
    at IncomingMessage.<anonymous> (/Users/hermanw/Documents/HermWong/phonegap-gui/build/PhoneGap/osx/PhoneGap.app/Contents/Resources/app.nw/node_modules/node-webkit-updater/node_modules/request/request.js:936:12)
    at IncomingMessage.EventEmitter.emit (events.js:126:20)
    at _stream_readable.js:895:16
```

I've tested using versions 0.2.3 and 0.2.4 of the `node-webkit-updater` module.

Currently the `manifestUrl` and `packages` properties are defined in `www/package.json`; the `manifestUrl` points to `package.json` in the project's root (not in the `www` folder), while the `packages` for `mac` and `win` are defined in `www/package.json`.

**Comment by hermwong** [comment]
It looks like the `node-webkit-updater` requires that the definition of the `packages` properties to be in the manifest file that is specified in the `manifestUrl`.
