### ISSUE TITLE
Minor Issue: Deleting App crashs Desktop App

### ISSUE THREAD

**Issue by SchadLucas** [phonegap/phonegap-app-desktop#314]
Hey there. I've found a little bug - not a critical one but still a bug.. ;)

Simply to reproduce:

- Start PG Desktop App
- Delete the with PG created App (the folder / content of the folder)
- Desktop App crashs

**Comment by hermwong** [comment]
Hi @SchadLucas,

I just wanted to get some clarification of where you are deleting your app from.

Are you deleting the your app (folder / contents of your folder) from your operating system (Windows / OSX) or the PhoneGap Desktop App?

**Comment by SchadLucas** [comment]
Hehe.. I delete **my** app - not the PhoneGap Desktop App ;)

2015-03-03 22:58 GMT+01:00 Herm Wong <notifications@github.com>:

**Comment by hermwong** [comment]
Did you delete your app using the delete feature in the PhoneGap Desktop App?

Or did you delete your app using the file explorer on your operating system (Finder on OSX or Windows Explorer on Windows)?

**Comment by SchadLucas** [comment]
Windows Explorer

**Comment by hermwong** [comment]
I wasn't able to reproduce this issue. I used Windows 8.1 and followed these steps:

1. Launched PhoneGap Desktop
1. I had 3 projects that had been loaded into PhoneGap Desktop from my previous session.
  1. `C:\Users\herm\Documents\HermWong\phonegap-gui\_testing\test01`
  1. `C:\Users\herm\Documents\HermWong\phonegap-gui\_testing\test02`
  1. `C:\Users\herm\Documents\HermWong\phonegap-gui\_testing\test03`
1. Launched Windows Explorer
1. Tried to delete the `C:\Users\herm\Documents\HermWong\phonegap-gui\_testing\test02` folder from Windows Explorer but got a warning dialog that prevented me deleting the folder (Windows would not allow me to delete the folder even if I press the `continue` button).

![win-delete-warning](https://cloud.githubusercontent.com/assets/107754/6538253/8fd1ccb8-c414-11e4-8a09-ae56ca84c10e.png)

**Comment by hermwong** [comment]
After further investigation, I was able to get the PhoneGap Desktop to crash following these steps (on Windows 8.1):

1. Launch PhoneGap Desktop
1. I had 3 projects that had been loaded into PhoneGap Desktop from my previous session.
  1. `C:\Users\herm\Documents\HermWong\phonegap-gui\_testing\test01`
  1. `C:\Users\herm\Documents\HermWong\phonegap-gui\_testing\test02`
  1. `C:\Users\herm\Documents\HermWong\phonegap-gui\_testing\test03`
1. Quit PhoneGap Desktop
1. Launch Windows Explorer
1. Delete the `C:\Users\herm\Documents\HermWong\phonegap-gui\_testing\test02` folder
1. Launch PhoneGap Desktop
1. None of the remaining projects seem to be set as an active project that the PhoneGap Desktop is serving
1. Click on the `play` button beside one of the remaining projects to set it as the active project for the PhoneGap Desktop to serve
1. The PhoneGap Desktop will crash and display the following error:

```
typeerror: Cannot read property 'projectId' of undefined    
at Server.<anonymous> (file:///Users/hermanw/Documents/HermWong/phonegap-gui/build/PhoneGap/osx/PhoneGap.app/Contents/Resources/app.nw/js/server-status.js:30:60)    
at Server.EventEmitter.emit (events.js:104:17)    
at /Users/hermanw/Documents/HermWong/phonegap-gui/build/PhoneGap/osx/PhoneGap.app/Contents/Resources/app.nw/node_modules/connect-phonegap/lib/serve.js:94:20    
at Request._callback (/Users/hermanw/Documents/HermWong/phonegap-gui/build/PhoneGap/osx/PhoneGap.app/Contents/Resources/app.nw/node_modules/connect-phonegap/lib/util/ip.js:52:9)    
at Request.self.callback (/Users/hermanw/Documents/HermWong/phonegap-gui/build/PhoneGap/osx/PhoneGap.app/Contents/Resources/app.nw/node_modules/connect-phonegap/node_modules/request/request.js:122:22)    
at Request.EventEmitter.emit (events.js:107:17)    
at Request.<anonymous> (/Users/hermanw/Documents/HermWong/phonegap-gui/build/PhoneGap/osx/PhoneGap.app/Contents/Resources/app.nw/node_modules/connect-phonegap/node_modules/request/request.js:888:14)    
at Request.EventEmitter.emit (events.js:126:20)    
at IncomingMessage.<anonymous> (/Users/hermanw/Documents/HermWong/phonegap-gui/build/PhoneGap/osx/PhoneGap.app/Contents/Resources/app.nw/node_modules/connect-phonegap/node_modules/request/request.js:839:12)    
at IncomingMessage.EventEmitter.emit (events.js:126:20)
```

I was also able to reproduce the crash on OSX.

**Comment by hermwong** [comment]
Once the project folder is deleted and the PhoneGap Desktop App is relaunched the project is removed from PG-Desktop's `localStorage` through the [`removeMissingProjects`](https://github.com/phonegap/phonegap-app-desktop/blob/master/www/js/local-storage.js#L72-L97) method.

The issue that causes the crash is that there is no `activeWidget` being set after the deleted projected has been removed.
