### ISSUE TITLE
Error: Cannot find module 'configstore'

### ISSUE THREAD

**Issue by peon501** [phonegap/phonegap-app-desktop#919]
### PhoneGap Desktop version 
0.4.5

### Computer OS version 
Ubuntu 19.10

### Is your network using a proxy? 
No

### Do you have multiple network adapters (or virtual network adapters)? 
No

### Are you using VPN? 
No

### Expected Behaviour
to run app
with electron www or electron . if in www dir

### Actual Behaviour
getting error

### Steps to Reproduce 
try to install it and use it
#### Error messages
```
App threw an error during load
Error: Cannot find module 'configstore'
Require stack:
- /home/matas/Desktop/apps-dev/phonegap-app-desktop-master/www/index.js
- /usr/local/lib/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:798:15)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7595:16)
    at Module._load (internal/modules/cjs/loader.js:691:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/matas/Desktop/apps-dev/phonegap-app-desktop-master/www/index.js:7:21)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)


```

**Comment by peon501** [comment]
if you fix it manually you get an error that u don't have some kind of os-name lib after that installed you when you run nothing happens and it just stays and doesn't start ap
